"""create blacklistedtokens table

Revision ID: 4420424eb216
Revises: 824db833f8b9
Create Date: 2025-07-19 10:24:12.031154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4420424eb216'
down_revision: Union[str, Sequence[str], None] = '824db833f8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklistedtokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blacklistedtokens_token'), 'blacklistedtokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blacklistedtokens_token'), table_name='blacklistedtokens')
    op.drop_table('blacklistedtokens')
    # ### end Alembic commands ###
