"""Add is_active field to URL table

Revision ID: 9a048e2556b1
Revises: dbeeed8605f2
Create Date: 2025-07-20 10:15:21.355422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a048e2556b1'
down_revision: Union[str, Sequence[str], None] = 'dbeeed8605f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'is_active')
    # ### end Alembic commands ###
